{% set name = "fx" %}
{% set version = "37.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/{{ version }}.tar.gz
  sha256: 1d81db387d804c43368f6f85c760242814da07363a15b329e8ff8d369b343e8a

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fx -v

about:
  home: https://github.com/antonmedv/fx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  dev_url: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
