{% set name = "fx" %}
{% set version = "35.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/{{ version }}.tar.gz
  sha256: 5ab642bb91ad9c1948de1add2d62acec22d82398e420957c191c1549999eb351

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fx -v

about:
  home: https://github.com/antonmedv/fx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  dev_url: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
