{% set name = "fx" %}
{% set version = "37.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/{{ version }}.tar.gz
  sha256: 75c8c360bac4bccbab85b4873b7030a4ed88d8d4a6e718a935851be6454fe56b

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fx -v

about:
  home: https://github.com/antonmedv/fx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  dev_url: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
