{% set name = "fx" %}
{% set version = "38.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/{{ version }}.tar.gz
  sha256: b9c4b935852cb9c3bae39b1c1293a8bfb010c5d79ce71a1ea6197002a5291613

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fx -v

about:
  home: https://github.com/antonmedv/fx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  dev_url: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
