{% set name = "fx" %}
{% set version = "39.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/{{ version }}.tar.gz
  sha256: ea1dbfd760f0ab664dba9bc4d49f4426b7a01f5beb70896527365321e997c57c

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fx -v

about:
  home: https://github.com/antonmedv/fx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  dev_url: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
