context:
  version: "40.0.0"

package:
  name: fx
  version: ${{ version }}

source:
  url: https://github.com/antonmedv/fx/archive/${{ version }}.tar.gz
  sha256: 92e5ade859952bc79a3c68492803ce0af25a7332c78c4a0e1914da302d88b478

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - fx -v

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Terminal JSON viewer
  homepage: https://github.com/antonmedv/fx
  repository: https://github.com/antonmedv/fx

extra:
  recipe-maintainers:
    - danielnachun
